name: Build Docker Image

# Docker Images are built on all pushes to preview
on:
  push:
    branches:
      - 'preview'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Debug
        run: echo ${{ env.REGISTRY }}/${{ github.repository }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # Push to Github Container Registry
          images: |
            ${{ env.REGISTRY }}/partylich/actual-server
          # Creates the following tags:
          # - actual-server:latest
          # - actual-server:1.3
          # - actual-server:1.3.7
          # - actual-server:sha-90dd603
          tags: |
            type=sha
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push standard image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          platforms: |
            linux/amd64
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/partylich/actual-server:latest
